# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_post.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Add_Post(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(422, 405)
        Dialog.setMinimumSize(QtCore.QSize(422, 405))
        Dialog.setMaximumSize(QtCore.QSize(422, 405))
        Dialog.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 50, 61, 16))
        self.label_2.setObjectName("label_2")
        self.line_add_FIO = QtWidgets.QLineEdit(Dialog)
        self.line_add_FIO.setGeometry(QtCore.QRect(140, 50, 231, 22))
        self.line_add_FIO.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_add_FIO.setObjectName("line_add_FIO")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 90, 41, 21))
        self.label_3.setObjectName("label_3")
        self.line_add_num = QtWidgets.QLineEdit(Dialog)
        self.line_add_num.setGeometry(QtCore.QRect(140, 90, 191, 22))
        self.line_add_num.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_add_num.setObjectName("line_add_num")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(60, 130, 55, 16))
        self.label_4.setObjectName("label_4")
        self.line_add_adress = QtWidgets.QLineEdit(Dialog)
        self.line_add_adress.setGeometry(QtCore.QRect(140, 130, 231, 22))
        self.line_add_adress.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_add_adress.setObjectName("line_add_adress")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(60, 170, 55, 16))
        self.label_5.setObjectName("label_5")
        self.line_add_passport = QtWidgets.QLineEdit(Dialog)
        self.line_add_passport.setGeometry(QtCore.QRect(140, 170, 191, 22))
        self.line_add_passport.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_add_passport.setObjectName("line_add_passport")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(60, 210, 55, 16))
        self.label_6.setObjectName("label_6")
        self.line_add_product = QtWidgets.QLineEdit(Dialog)
        self.line_add_product.setGeometry(QtCore.QRect(140, 210, 191, 22))
        self.line_add_product.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_add_product.setObjectName("line_add_product")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(150, 270, 93, 61))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавить поставщика"))
        self.label_2.setText(_translate("Dialog", "ФИО"))
        self.label_3.setText(_translate("Dialog", "Номер"))
        self.label_4.setText(_translate("Dialog", "Адрес"))
        self.label_5.setText(_translate("Dialog", "Паспорт"))
        self.label_6.setText(_translate("Dialog", "Поставка"))
        self.pushButton.setText(_translate("Dialog", "Добавить"))
