# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_stocks.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Add_Stocks(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(290, 320)
        Dialog.setMinimumSize(QtCore.QSize(290, 320))
        Dialog.setMaximumSize(QtCore.QSize(290, 320))
        Dialog.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 41, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 70, 81, 31))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(40, 120, 51, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 160, 101, 31))
        self.label_6.setObjectName("label_6")
        self.line_add_adress = QtWidgets.QLineEdit(Dialog)
        self.line_add_adress.setGeometry(QtCore.QRect(80, 40, 171, 22))
        self.line_add_adress.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_add_adress.setObjectName("line_add_adress")
        self.line_add_vmestimost = QtWidgets.QLineEdit(Dialog)
        self.line_add_vmestimost.setGeometry(QtCore.QRect(110, 80, 113, 22))
        self.line_add_vmestimost.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_add_vmestimost.setObjectName("line_add_vmestimost")
        self.line_add_status = QtWidgets.QLineEdit(Dialog)
        self.line_add_status.setGeometry(QtCore.QRect(90, 130, 113, 22))
        self.line_add_status.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_add_status.setObjectName("line_add_status")
        self.line_add_zagruzh = QtWidgets.QLineEdit(Dialog)
        self.line_add_zagruzh.setGeometry(QtCore.QRect(140, 170, 113, 22))
        self.line_add_zagruzh.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_add_zagruzh.setObjectName("line_add_zagruzh")
        self.btn_add = QtWidgets.QPushButton(Dialog)
        self.btn_add.setGeometry(QtCore.QRect(90, 230, 93, 61))
        self.btn_add.setObjectName("btn_add")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавление"))
        self.label_2.setText(_translate("Dialog", "Адрес"))
        self.label_3.setText(_translate("Dialog", "Вместимость"))
        self.label_5.setText(_translate("Dialog", "Статус"))
        self.label_6.setText(_translate("Dialog", "Загруженность"))
        self.btn_add.setText(_translate("Dialog", "Добавить"))
