# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'del_pokup.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Del_Pokup(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(297, 165)
        Dialog.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line_del_pokup = QtWidgets.QLineEdit(Dialog)
        self.line_del_pokup.setGeometry(QtCore.QRect(100, 50, 113, 22))
        self.line_del_pokup.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_del_pokup.setObjectName("line_del_pokup")
        self.btn_del_pokup = QtWidgets.QPushButton(Dialog)
        self.btn_del_pokup.setGeometry(QtCore.QRect(110, 110, 93, 28))
        self.btn_del_pokup.setObjectName("btn_del_pokup")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Удаление"))
        self.label.setText(_translate("Dialog", "Введите id для удаления"))
        self.btn_del_pokup.setText(_translate("Dialog", "Удалить"))
