# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'del_post.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Del_Post(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 156)
        Dialog.setMinimumSize(QtCore.QSize(400, 156))
        Dialog.setMaximumSize(QtCore.QSize(400, 156))
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 10, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line_del_post = QtWidgets.QLineEdit(Dialog)
        self.line_del_post.setGeometry(QtCore.QRect(140, 50, 113, 22))
        self.line_del_post.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_del_post.setObjectName("line_del_post")
        self.btn_del_post = QtWidgets.QPushButton(Dialog)
        self.btn_del_post.setGeometry(QtCore.QRect(150, 90, 93, 28))
        self.btn_del_post.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Удаление"))
        self.label.setText(_translate("Dialog", "Введите id поставщика для удаления"))
        self.btn_del_post.setText(_translate("Dialog", "Удалить"))
