# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'del_product.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Del_Product(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 173)
        Dialog.setMinimumSize(QtCore.QSize(400, 173))
        Dialog.setMaximumSize(QtCore.QSize(400, 173))
        Dialog.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(120, 10, 151, 16))
        self.label.setObjectName("label")
        self.line_del_product = QtWidgets.QLineEdit(Dialog)
        self.line_del_product.setGeometry(QtCore.QRect(140, 50, 113, 22))
        self.line_del_product.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_del_product.setObjectName("line_del_product")
        self.btn_del_product = QtWidgets.QPushButton(Dialog)
        self.btn_del_product.setGeometry(QtCore.QRect(150, 110, 93, 28))
        self.btn_del_product.setObjectName("btn_del_product")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Удаление"))
        self.label.setText(_translate("Dialog", "Введите id для удаления"))
        self.btn_del_product.setText(_translate("Dialog", "Удалить"))
