# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 10, 261, 81))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_stocks = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stocks.setGeometry(QtCore.QRect(40, 430, 111, 61))
        self.btn_stocks.setObjectName("btn_stocks")
        self.btn_post = QtWidgets.QPushButton(self.centralwidget)
        self.btn_post.setGeometry(QtCore.QRect(240, 430, 111, 61))
        self.btn_post.setObjectName("btn_post")
        self.btn_pokup = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pokup.setGeometry(QtCore.QRect(460, 430, 111, 61))
        self.btn_pokup.setObjectName("btn_pokup")
        self.btn_product = QtWidgets.QPushButton(self.centralwidget)
        self.btn_product.setGeometry(QtCore.QRect(650, 430, 111, 61))
        self.btn_product.setObjectName("btn_product")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Главное окно"))
        self.label.setText(_translate("MainWindow", "Добро пожаловать"))
        self.btn_stocks.setText(_translate("MainWindow", "Склады"))
        self.btn_post.setText(_translate("MainWindow", "Поставщики"))
        self.btn_pokup.setText(_translate("MainWindow", "Покупатели"))
        self.btn_product.setText(_translate("MainWindow", "Список товаров"))
