# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pokup.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Pokup(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1074, 515)
        Dialog.setMinimumSize(QtCore.QSize(1074, 515))
        Dialog.setMaximumSize(QtCore.QSize(1074, 515))
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(60, 110, 971, 241))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(162)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(470, 20, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_update_pokup = QtWidgets.QPushButton(Dialog)
        self.btn_update_pokup.setGeometry(QtCore.QRect(60, 400, 171, 71))
        self.btn_update_pokup.setObjectName("btn_update_pokup")
        self.btn_add_pokup = QtWidgets.QPushButton(Dialog)
        self.btn_add_pokup.setGeometry(QtCore.QRect(440, 400, 171, 71))
        self.btn_add_pokup.setObjectName("btn_add_pokup")
        self.btn_del_pokup = QtWidgets.QPushButton(Dialog)
        self.btn_del_pokup.setGeometry(QtCore.QRect(850, 400, 171, 71))
        self.btn_del_pokup.setObjectName("btn_del_pokup")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Покупатели"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ФИО"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Адрес"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Номер"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Адрес доставки"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Дата доставки"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Ожидаемый товар"))
        self.label.setText(_translate("Dialog", "Покупатели"))
        self.btn_update_pokup.setText(_translate("Dialog", "Обновить"))
        self.btn_add_pokup.setText(_translate("Dialog", "Добавить"))
        self.btn_del_pokup.setText(_translate("Dialog", "Удалить"))
