# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'post.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Post(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(814, 442)
        Dialog.setMinimumSize(QtCore.QSize(814, 442))
        Dialog.setMaximumSize(QtCore.QSize(814, 442))
        Dialog.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(50, 70, 731, 241))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(182)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(340, 20, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_update_post = QtWidgets.QPushButton(Dialog)
        self.btn_update_post.setGeometry(QtCore.QRect(40, 350, 131, 61))
        self.btn_update_post.setObjectName("btn_update_post")
        self.btn_add_post = QtWidgets.QPushButton(Dialog)
        self.btn_add_post.setGeometry(QtCore.QRect(330, 350, 131, 61))
        self.btn_add_post.setObjectName("btn_add_post")
        self.btn_del_post = QtWidgets.QPushButton(Dialog)
        self.btn_del_post.setGeometry(QtCore.QRect(640, 350, 131, 61))
        self.btn_del_post.setObjectName("btn_del_post")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Поставщики"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ФИО"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Номер"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Адрес"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Паспорт"))
        self.label.setText(_translate("Dialog", "Поставщики"))
        self.btn_update_post.setText(_translate("Dialog", "Обновить"))
        self.btn_add_post.setText(_translate("Dialog", "Добавить"))
        self.btn_del_post.setText(_translate("Dialog", "Удалить"))
