# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'product.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Product(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(952, 557)
        Dialog.setMinimumSize(QtCore.QSize(900, 517))
        Dialog.setMaximumSize(QtCore.QSize(1500, 800))
        Dialog.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(20, 130, 911, 231))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(152)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(440, 30, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_update_product = QtWidgets.QPushButton(Dialog)
        self.btn_update_product.setGeometry(QtCore.QRect(100, 420, 121, 61))
        self.btn_update_product.setObjectName("btn_update_product")
        self.btn_add_product = QtWidgets.QPushButton(Dialog)
        self.btn_add_product.setGeometry(QtCore.QRect(460, 420, 121, 61))
        self.btn_add_product.setObjectName("btn_add_product")
        self.btn_del_product = QtWidgets.QPushButton(Dialog)
        self.btn_del_product.setGeometry(QtCore.QRect(770, 420, 121, 61))
        self.btn_del_product.setObjectName("btn_del_product")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Товары"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Наименование"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Поставщик"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Покупатель"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Склад"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Стоимость"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Статус"))
        self.label.setText(_translate("Dialog", "Товары"))
        self.btn_update_product.setText(_translate("Dialog", "Обновить"))
        self.btn_add_product.setText(_translate("Dialog", "Добавить"))
        self.btn_del_product.setText(_translate("Dialog", "Удалить"))
