# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stocks.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Stocks(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(876, 502)
        Dialog.setMinimumSize(QtCore.QSize(876, 502))
        Dialog.setMaximumSize(QtCore.QSize(876, 502))
        Dialog.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(400, 0, 91, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(90, 90, 681, 241))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(170)
        self.btn_add_stocks = QtWidgets.QPushButton(Dialog)
        self.btn_add_stocks.setGeometry(QtCore.QRect(380, 410, 131, 51))
        self.btn_add_stocks.setObjectName("btn_add_stocks")
        self.btn_del_stocks = QtWidgets.QPushButton(Dialog)
        self.btn_del_stocks.setGeometry(QtCore.QRect(690, 410, 131, 51))
        self.btn_del_stocks.setObjectName("btn_del_stocks")
        self.btn_update_stocks = QtWidgets.QPushButton(Dialog)
        self.btn_update_stocks.setGeometry(QtCore.QRect(60, 410, 131, 51))
        self.btn_update_stocks.setObjectName("btn_update_stocks")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Склады"))
        self.label.setText(_translate("Dialog", "Склады"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Адрес"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Вместимость"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Статус"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Загруженость"))
        self.btn_add_stocks.setText(_translate("Dialog", "Добавить "))
        self.btn_del_stocks.setText(_translate("Dialog", "Удалить"))
        self.btn_update_stocks.setText(_translate("Dialog", "Обновить"))
